### ISSUE TITLE
Copy Activity Feature

### ISSUE THREAD

**Issue by nichr24** [RobertPorterfield/WAR#16]
Allow users to create new activity for current week using existing activity's fields.

Within activity modal for prior week items (?), add  Copy icon (with description text on mouse hover) near close icon.

Icon pack already loaded: @uifabric/icons

**Comment by RobertPorterfield** [comment]
Feedback from training and some OZI users indicates a "Copy Activity" feature would be appreciated. This would start a new Activity by copying all existing fields except for the date.
